language: groovy
jdk:
  - openjdk6
script: ./gradlew test
notifications:
  email: false
env:
  global:
  - secure: "Te7/gV9ApAi9Amo9THskyF3R+zIcMUgTI9kr2xRxNM0l3tN9N1sCv7CvxoabzHniSofKUOlI7Lhq/0gDIaWXYvNow73QhUkf0Oz5npFRITm3BdpVZxu/ZIQ4OR0edLRgmnRoRKqnfWWLEivu7YNOn9jkAQ7D/uBifsIrWWdX8uI="
  - secure: "pzsIaEvi1N3BiWOQMNCwcu7t5YLNLB13DfewRJUvXdbhpwWw3GAeVBBxQELXYyoxWBQn2TFCm6Qva2lmXZx+H+BwpBAqM9Txv4jaCKEMxVDjpRU2HIzoWfJ5lEKO7FgonMOs5VqMv5Ig3Ub0m+sX7LS92nRPBkHhYllG0VvmfR0="
after_success:
  - ! '[[ $TRAVIS_BRANCH =~ ^(v[0-9]+\.[0-9]+\.[0-9]+|master)$ && $TRAVIS_PULL_REQUEST
    = false ]] && ./gradlew install uploadArchives'
